version: "3.8"

services:
  # This service just builds the image. No changes are needed here.
  ros_dev_env:
    build: 
      context: .
      dockerfile: Dockerfile
    image: pr_robotics

  # This service runs the GUI container with added GPU hardware acceleration.
  gui_container:
    image: pr_robotics
    runtime: nvidia  # <-- ADDED: Use the NVIDIA Container Toolkit
    network_mode: host
    privileged: true
    environment:
      # Environment variables for GPU access and GUI forwarding
      - "NVIDIA_VISIBLE_DEVICES=all"      # <-- ADDED: Makes all GPUs available
      - "NVIDIA_DRIVER_CAPABILITIES=all"  # <-- ADDED: Provides necessary driver capabilities
      - "DISPLAY=${DISPLAY}"              # Your existing display variable
      - "QT_X11_NO_MITSHM=1"              # Your existing Qt setting
    volumes:
      # Volumes for GUI forwarding
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${HOME}/.Xauthority:/root/.Xauthority:rw
      # Your existing custom volumes
      - /dev:/dev
      - ./pr_robotics:/root/catkin_ws/src/pr_robotics
    devices:
      # Your existing custom device
      - "/dev/ttyUSB0"
    stdin_open: true
    tty: true